blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

urlpatterns = patterns('blog.views',
	url(r'^filter$', 'archive'),
	url(r'^post/(?P<id>\d+)/$', 'viewBlogPost'),
    #url(r'$', 'archive'),
    )

core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^blog/', include('blog.urls')),
	url(r'^$', 'blog.views.archive'),
)

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
import datetime
from django.contrib import admin
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

class BlogPost(models.Model):
	title = models.CharField(max_length=150)
	body = models.TextField()
	timestamp = models.DateTimeField(editable=False)
	tags = models.ManyToManyField('Tag')
	commentsCounter = models.PositiveIntegerField(default=0,editable=False)

	def incrementComment(self):
		self.commentsCounter += 1
		self.save(update_fields=['commentsCounter'])

	def decrementComment(self):
		self.commentsCounter -= 1
		self.save(update_fields=['commentsCounter'])

	class Meta:
		ordering = ('-timestamp',)

	def save(self, *args, **kwargs):
		if self.id == None:
			self.timestamp = datetime.datetime.today()
		super(BlogPost, self).save(*args, **kwargs)

	def __unicode__(self):
		return self.title

class Tag(models.Model):
	name = models.CharField(max_length=30, unique=True)

	class Meta:
		ordering = ('name',)

	def __unicode__(self):
		return self.name

class Comment(models.Model):
	author = models.CharField(max_length=30)
	timestamp = models.DateTimeField(editable=False)
	comment = models.TextField()
	blogPost = models.ForeignKey('BlogPost')

	class Meta:
		ordering = ('timestamp',)

	def save(self, *args, **kwargs):
		if self.id == None:
			self.timestamp = datetime.datetime.today()
			self.blogPost.incrementComment()
		super(Comment, self).save(*args, **kwargs)

@receiver(pre_delete, sender=Comment)
def comment_delete(sender, instance, **kwargs):
	instance.blogPost.decrementComment()


"""Admin Models"""

class BlogPostAdmin(admin.ModelAdmin):
	list_display = ('title', 'timestamp',)

class TagAdmin(admin.ModelAdmin):
	list_display = ('name',)

class CommentAdmin(admin.ModelAdmin):
	list_display = ('author','blogPost')

admin.site.register(BlogPost, BlogPostAdmin)
admin.site.register(Tag, TagAdmin)
admin.site.register(Comment, CommentAdmin)

blog/forms.py
# -*- coding: utf-8 -*-
from django import forms
from blog.models import Comment
from blog.models import BlogPost

class AddCommentForm(forms.Form):
	author = forms.CharField(max_length=30)
	message = forms.CharField(widget=forms.Textarea)

	class Meta:
		model = Comment

blog/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import redirect
from django.shortcuts import render
from blog.models import BlogPost
from blog.models import Comment
from blog.forms import AddCommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def archive(request):
    if request.method == 'GET':
        tag = request.GET.get('tag')
        if tag:
            posts = BlogPost.objects.filter(tags__name__contains=tag)
        else:
            posts = BlogPost.objects.all()
        paginator = Paginator(posts, 10)
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        return render(request, 'archive.html', {'posts': posts})

def viewBlogPost(request,id):
    try:
        blogPost = BlogPost.objects.get(pk=id)
        comments = Comment.objects.filter(blogPost = blogPost)
        if request.method == 'POST':
            form = AddCommentForm(request.POST)
            if form.is_valid():
                newComment = Comment()
                newComment.blogPost = blogPost
                newComment.author = form.cleaned_data['author']
                newComment.comment = form.cleaned_data['message']
                newComment.save()
        else:
            form = AddCommentForm()
        return render(request, 'blogentry.html',{'post': blogPost, 'comments': comments, 'form':form})
    except BlogPost.DoesNotExist:
        return redirect('blog.views.archive')

templates/archive.html
{% extends "base.html" %}
{% block content %}
{% for post in posts %}
<div class="box">
    <div class="caption">
	    <h2><a href ={% url "blog.views.viewBlogPost" post.pk %}>{{ post.title }}</a></h2>
    </div>
    <div class="text">
	    <p>{{ post.body }}</p>
    </div>
</div>
<div class="box">
    <p>Запись опубликована: {{ post.timestamp }}</p>
    <p>Теги:
        {%for tag in post.tags.all %}
			<a href ={% url "blog.views.archive" %}?tag={{ tag }}>{{tag}}</a>
        {% endfor %}</p>
	<p>Количество комментариев: {{ post.commentsCounter }}</p>

</div>
{% endfor %}
<div class="box">
	<p>{% if posts.has_previous %}
	    	<a href="?page={{ posts.previous_page_number }}">Назад</a>
       {% endif %}
            Страница {{ posts.number }} из {{ posts.paginator.num_pages }}.
       {% if posts.has_next %}
			<a href="?page={{ posts.next_page_number }}">Вперед</a>
       {% endif %}</p>
</div>

{% endblock %}

templates/base.html
<html>
{% load staticfiles %}
<head>
<link href="{% static "css/style.css" %}" rel="stylesheet" />
</head>
<body>
<h1><a href="/">Blog Application</a></h1>

<div class="box">
	<form action="/blog/filter">
		<div class="input_text">
		<span>Поиск по тэгам:</span><input type="text" class="input_text" name="tag">
		<input type="submit" class="button" value="Искать">
	    </div>
	</form>
</div>

{% block content %}
{% endblock %}
</body>
</html>

templates/blogentry.html
{% extends "base.html" %}
{% block content %}
<div class="box">
    <div class="caption">
	    <h2>{{ post.title }}</h2>
	</div>
    <div class="text">
		<p>{{ post.body }}</p>
	</div>
		<p>Запись опубликована: {{ post.timestamp }}</p>
		<p>Теги:
            {%for tag in post.tags.all %}
				<a href ={% url "blog.views.archive" %}?tag={{ tag }}>{{tag}}</a>
            {% endfor %}</p>
</div>
<div class="box"><p>Количество комментариев: {{ post.commentsCounter }}</p></div>
{% for comment in comments %}
	<div class="box">
    	<span>Автор: {{ comment.author }}</span>
    	<p>{{ comment.comment }}</p>
    	<p>Ответил: {{ comment.timestamp }}</p>
	</div>
{% endfor %}


<form action="" method="post">{% csrf_token %}
	<div class="box">
        {{ form.non_field_errors }}
            {{ form.author.errors }}
			<label for="id_author">Ваше имя:</label>
			<input class="input_text" id="id_author" maxlength="30" name="author" type="text" />
            {{ form.message.errors }}
			<label for="id_message">Текст комментария:</label>
			<textarea class="message" cols="40" id="id_message" name="message" rows="10"></textarea>
			<input type="submit" class="button" value="Отправить" />
		</div>
	</form>
{% endblock %}